.\" Process this file with
.\" groff -man -Tascii bam-rmdup.1
.\"
.TH BIOHAZARD 1 "DECEMBER 2012" Miscellanea "User Manuals"
.SH NAME
biohazard \- library and tools working mostly with BAM files
.SH SYNOPSIS
.B bam-meld
.B bam-rmdup

.SH DESCRIPTION
.B biohazard
is chiefly a Haskell library that reads and writes BAM files, along with
some algorithms and tools.  See the Haskell Library documentation and
the individual programs' man pages for details.

.SH AUTHOR
Udo Stenzel <udo_stenzel@eva.mpg.de>

.SH "SEE ALSO"
.BR bam-fixpair (1)
.BR bam-meld (1)
.BR bam-rewrap (1)
.BR bam-rmdup (1)
.BR fastq2bam (1)
.BR jivebunny (1)
.BR http://samtools.sourceforge.net/SAM1.pdf

